"""empty message

Revision ID: 7b4bbbd07423
Revises: fe187d88ac20
Create Date: 2021-10-19 14:53:20.426731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4bbbd07423'
down_revision = 'fe187d88ac20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_sala', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'sala', ['id_sala'], ['id_sala'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'id_sala')
    # ### end Alembic commands ###
