"""empty message

Revision ID: 8e30d28f0dd0
Revises: 97d6022734cc
Create Date: 2021-10-27 22:02:41.130407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30d28f0dd0'
down_revision = '97d6022734cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sala', sa.Column('nome_sala', sa.String(length=30), nullable=False))
    op.add_column('sala', sa.Column('descricao_sala', sa.String(length=150), nullable=True))
    op.add_column('sala', sa.Column('tempo_mensagem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sala', 'tempo_mensagem')
    op.drop_column('sala', 'descricao_sala')
    op.drop_column('sala', 'nome_sala')
    # ### end Alembic commands ###
