"""empty message

Revision ID: 93d999987dad
Revises: b698b1eddb8a
Create Date: 2021-09-30 21:03:35.163140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d999987dad'
down_revision = 'b698b1eddb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pergunta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pergunta',
    sa.Column('id_pergunta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_respondida', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_sala', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], name='pergunta_id_sala_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_user'], name='pergunta_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_pergunta', name='pergunta_pkey')
    )
    # ### end Alembic commands ###
