"""empty message

Revision ID: 9cf86a948da8
Revises: 8e30d28f0dd0
Create Date: 2021-10-27 23:15:59.268791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf86a948da8'
down_revision = '8e30d28f0dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id_mensagem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id_usuario_mensagem', sa.Integer(), nullable=False),
    sa.Column('id_sala_mensagem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala_mensagem'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['id_usuario_mensagem'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    op.add_column('pergunta', sa.Column('id_usuario_pergunta', sa.Integer(), nullable=False))
    op.add_column('pergunta', sa.Column('id_sala_pergunta', sa.Integer(), nullable=False))
    op.drop_constraint('pergunta_id_usuario_fkey', 'pergunta', type_='foreignkey')
    op.drop_constraint('pergunta_id_sala_fkey', 'pergunta', type_='foreignkey')
    op.create_foreign_key(None, 'pergunta', 'sala', ['id_sala_pergunta'], ['id_sala'])
    op.create_foreign_key(None, 'pergunta', 'usuario', ['id_usuario_pergunta'], ['id_usuario'])
    op.drop_column('pergunta', 'id_sala')
    op.drop_column('pergunta', 'id_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pergunta', sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pergunta', sa.Column('id_sala', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pergunta', type_='foreignkey')
    op.drop_constraint(None, 'pergunta', type_='foreignkey')
    op.create_foreign_key('pergunta_id_sala_fkey', 'pergunta', 'sala', ['id_sala'], ['id_sala'])
    op.create_foreign_key('pergunta_id_usuario_fkey', 'pergunta', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_column('pergunta', 'id_sala_pergunta')
    op.drop_column('pergunta', 'id_usuario_pergunta')
    op.drop_table('mensagem')
    # ### end Alembic commands ###
