"""empty message

Revision ID: a77b1a66fca4
Revises: c44b456e94cd
Create Date: 2021-10-05 23:15:50.927011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77b1a66fca4'
down_revision = 'c44b456e94cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'usuario', 'sala', ['id_sala'], ['id_sala'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    # ### end Alembic commands ###
