"""empty message

Revision ID: b60a1086319d
Revises: 
Create Date: 2021-10-04 19:26:58.818533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60a1086319d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sala_id_moderador_fkey', 'sala', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sala_id_moderador_fkey', 'sala', 'usuario', ['id_moderador'], ['id_user'])
    # ### end Alembic commands ###
