"""empty message

Revision ID: b698b1eddb8a
Revises: c316d558aa07
Create Date: 2021-09-30 20:33:10.136534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b698b1eddb8a'
down_revision = 'c316d558aa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sala', ['id_moderador'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sala', type_='unique')
    # ### end Alembic commands ###
