"""Adicionando coluna id_sala no usuario

Revision ID: c316d558aa07
Revises: eaec3fca713a
Create Date: 2021-09-28 23:03:43.679728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c316d558aa07'
down_revision = 'eaec3fca713a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'usuario', 'sala', ['id_sala'], ['id_sala'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    # ### end Alembic commands ###
