"""empty message

Revision ID: dc00da42a3a2
Revises: b60a1086319d
Create Date: 2021-10-04 19:27:46.455716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc00da42a3a2'
down_revision = 'b60a1086319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sala_id_moderador_fkey', 'sala', 'usuario', ['id_moderador'], ['id_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sala_id_moderador_fkey', 'sala', type_='foreignkey')
    # ### end Alembic commands ###
