"""empty message

Revision ID: eaec3fca713a
Revises: 
Create Date: 2021-09-28 22:59:31.831230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaec3fca713a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('sala',
    sa.Column('id_sala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_moderador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_moderador'], ['usuario.id_user'], ),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('pergunta',
    sa.Column('id_pergunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('is_respondida', sa.Boolean(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_user'], ),
    sa.PrimaryKeyConstraint('id_pergunta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pergunta')
    op.drop_table('usuario')
    op.drop_table('sala')
    # ### end Alembic commands ###
