"""empty message

Revision ID: fe187d88ac20
Revises: 
Create Date: 2021-10-19 14:52:56.925567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe187d88ac20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('sala',
    sa.Column('id_sala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_moderador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_moderador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sala'),
    sa.UniqueConstraint('id_moderador')
    )
    op.create_table('pergunta',
    sa.Column('id_pergunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('is_respondida', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pergunta')
    )
    op.create_table('usuarios_concordam',
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id_pergunta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pergunta', 'id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_concordam')
    op.drop_table('pergunta')
    op.drop_table('sala')
    op.drop_table('usuario')
    # ### end Alembic commands ###
